"""
Generate maneuver extension artifacts.

Reads tools/extension_profiles.py and produces:
  1. .txt files in Aerobatics_sample_inputs/ for each maneuver
  2. tools/_profiles_snippet.py — entries to splice into PROFILES dict in
     aerobatic_profiles.py
  3. tools/_catalog_snippet.py — register() calls to append to
     maneuvers_catalog.py

The generator validates each profile's row count before writing and rejects
malformed inputs.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.extension_profiles import ALL_EXTENSIONS  # noqa: E402

PROFILE_DIR = ROOT / "Aerobatics_sample_inputs"
SNIPPET_PROFILES = ROOT / "tools" / "_profiles_snippet.py"
SNIPPET_CATALOG = ROOT / "tools" / "_catalog_snippet.py"


def _format_profile_file(rows) -> str:
    lines = [str(len(rows))]
    for nz, dur_ms in rows:
        # Match existing format: "Nz, duration_ms" with one decimal for Nz
        lines.append(f"{nz}, {dur_ms}")
    lines.append("")  # trailing newline matching existing files
    return "\n".join(lines)


def _category_to_meta(category: str) -> dict:
    return {
        "championship": {"category_enum": "ManeuverCategory.CHAMPIONSHIP"},
        "military_acm": {"category_enum": "ManeuverCategory.MILITARY_ACM"},
        "extreme_post_stall": {"category_enum": "ManeuverCategory.EXTREME_POST_STALL"},
    }[category]


def main() -> None:
    PROFILE_DIR.mkdir(exist_ok=True)
    written = []
    profiles_lines = []
    catalog_lines = []

    for ident, meta in ALL_EXTENSIONS.items():
        rows = meta["rows"]
        # 1) Write .txt
        txt = _format_profile_file(rows)
        (PROFILE_DIR / meta["filename"]).write_text(txt, encoding="utf-8")
        written.append(meta["filename"])

        # 2) PROFILES dict snippet
        desc = meta["description"].replace('"', '\\"')
        profiles_lines.append(
            f'    "{ident}": ("{meta["filename"]}", "{desc}"),'
        )

        # 3) CATALOG register snippet
        cat_meta = _category_to_meta(meta["category"])
        kwargs = [
            f'identifier="{ident}"',
            f'category={cat_meta["category_enum"]}',
            f'description="{desc}"',
            f'aircraft="{meta["aircraft"]}"',
            f'peak_pos_gz={meta["peak_pos_gz"]}',
            f'peak_neg_gz={meta["peak_neg_gz"]}',
            f'onset_rate_g_per_s={meta["onset_g_per_s"]}',
            f'total_duration_s={meta["total_dur_s"]}',
        ]
        if meta.get("aresti_family") is not None:
            kwargs.append(f'aresti_family={meta["aresti_family"]}')
        if meta.get("sustained_gz") is not None:
            kwargs.append(f'sustained_gz={meta["sustained_gz"]}')
        if meta.get("sustained_dur_s") is not None:
            kwargs.append(f'sustained_duration_s={meta["sustained_dur_s"]}')
        if meta.get("hemodynamic_concern"):
            hc = meta["hemodynamic_concern"].replace('"', '\\"')
            kwargs.append(f'hemodynamic_concern="{hc}"')
        if meta.get("source"):
            src = meta["source"].replace('"', '\\"')
            kwargs.append(f'source="{src}"')

        catalog_lines.append(
            "register(ManeuverMeta(\n    "
            + ",\n    ".join(kwargs)
            + ",\n))"
        )

    # Emit snippets
    SNIPPET_PROFILES.write_text(
        "# AUTO-GENERATED by tools/generate_extension.py — splice into "
        "aerobatic_profiles.py PROFILES dict.\n\n"
        + "\n".join(profiles_lines) + "\n",
        encoding="utf-8",
    )
    SNIPPET_CATALOG.write_text(
        "# AUTO-GENERATED by tools/generate_extension.py — append to "
        "maneuvers_catalog.py after the existing register(...) calls.\n"
        "# Requires: from maneuvers_catalog import register, ManeuverMeta, "
        "ManeuverCategory\n\n"
        + "\n\n".join(catalog_lines) + "\n",
        encoding="utf-8",
    )

    print(f"[ok] wrote {len(written)} .txt files to {PROFILE_DIR}")
    print(f"[ok] PROFILES snippet → {SNIPPET_PROFILES}")
    print(f"[ok] CATALOG snippet → {SNIPPET_CATALOG}")


if __name__ == "__main__":
    main()
